apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financial-db-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: financial.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: financial-db-api
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: financial-db-app
                port:
                  number: 8501
